apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guardian-service
  labels:
    rbac.authorization.k8s.io/guardian: 'true'
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - guard.security.knative.dev
    resources:
      - guardians
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guard-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guardian-admin
subjects:
  - kind: ServiceAccount
    name: guard-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: guardian-service
  