apiVersion: apps/v1
kind: Deployment
metadata:
  name: guard-service
  namespace: knative-serving
  labels:
    app: guard-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guard-service
  template:
    metadata:
      labels:
        app: guard-service
    spec:
#      imagePullSecrets:
#      - name: all-icr-io
      serviceAccountName: guard-service-account
      volumes:
      - name: guard-service-tls-volume
        secret:
          secretName: knative-serving-certs
      containers:
      - name: guard-service
        image: ko://knative.dev/security-guard/cmd/guard-service
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /secrets
          name: guard-service-tls-volume
        ports:
          - containerPort: 8888
        env:
          - name: GUARD_SERVICE_LABELS
            value: ""
          - name: GUARD_SERVICE_TLS
            value: "false"
          - name: GUARD_SERVICE_AUTH
            value: "false"
          - name: GUARD_SERVICE_LOG_LEVEL
            value: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: guard-service
  namespace: knative-serving
spec:
  selector:
    app: guard-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8888
